[package]
name = "lesson3-russian-roulette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { path = "../rand" }
lesson1-sampling = { path = "../lesson1-sampling" }
