[package]
name = "video2-montecarlo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { path = "../rand" }
video1-sampling = { path = "../video1-sampling" }
